apiVersion: v1
kind: Pod
metadata:
  name: pod-multitool
  labels:
    app: multitool
spec:
  containers:
    - name: multitool
      image: praqma/network-multitool:alpine-extra
      resources:
      ports:
        - name: "http"
          containerPort: 8090
      livenessProbe:
        tcpSocket:
          port: 8090
        initialDelaySeconds: 10
        timeoutSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 8090

